# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(800, 486)
        font = QtGui.QFont()
        font.setPointSize(1)
        Interface.setFont(font)
        self.label = QtWidgets.QLabel(Interface)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Monospaced")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Interface)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 781, 271))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Interface)
        self.pushButton.setGeometry(QtCore.QRect(350, 430, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Monospaced")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Interface)
        self.label_2.setGeometry(QtCore.QRect(10, 85, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Monospaced")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "Interface"))
        self.label.setText(_translate("Interface", "Personal Organizer"))
        self.pushButton.setText(_translate("Interface", "Insert"))
        self.label_2.setText(_translate("Interface", "Enter your daily activity here :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interface = QtWidgets.QWidget()
    ui = Ui_Interface()
    ui.setupUi(Interface)
    Interface.show()
    sys.exit(app.exec_())
